version: "3.9"
services:
  bread_bot:
    image: bread_bot:base
    command: bash -c "alembic upgrade head && python server.py"
    ports:
      - "8080:8080"
    volumes:
      - ../.:/code/:ro
    env_file:
      - ../../environments.env
    networks:
      - bread_bot_net
  pgbouncer:
    image: edoburu/pgbouncer
    env_file:
      - ../../pgbouncer.env
    ports:
      - "5432:5432"
    networks:
      - bread_bot_net
networks:
  bread_bot_net:
    external: True
