version: "3.9"
services:
  bread_bot:
    image: bread_bot:base
    command: python server.py
    ports:
      - "9191:9191"
    volumes:
      - ../.:/code/:ro
    env_file:
      - ../../environments.env
    networks:
      - bread_bot_net

networks:
  bread_bot_net:
    external: True
