filebeat.inputs:
- type: container
  paths:
    - '/var/lib/docker/containers/*/*.log'

processors:
- add_docker_metadata:
    host: "unix:///var/run/docker.sock"
- decode_json_fields:
    fields: ["log"]
    target: "json"
    overwrite_keys: true

output.elasticsearch:
  hosts: [elasticsearch]
  username: "${ELASTICSEARCH_USERNAME}"
  password: "${ELASTICSEARCH_PASSWORD}"

setup.kibana:
  host: "kibana"

logging.json: true
logging.metrics.enabled: false
